### ISSUE TITLE
Unable to run locuplot

### ISSUE THREAD

**Issue by vtortola** [pawndev/locuplot#1]
Hi!

I installed locuplot and wanted to see a rendered example, so I cloned this repository and tried to run it as explained in the documentation, but I got this error:

```
$ locuplot --version
locuplot (version 0.1.3)

$ git clone git@github.com:pawndev/locuplot.git
[...]

$ cd locuplot

$ locuplot -d example/stats -p sample -e dist
Traceback (most recent call last):
  File "/usr/local/bin/locuplot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/locuplot/main.py", line 23, in main
    history_figures = stats.history.generate_all_plot()
  File "/usr/local/lib/python3.8/site-packages/locuplot/locust/history_stats.py", line 41, in generate_all_plot
    req_per_sec_d3 = mpld3.fig_to_html(req_per_sec_figure)
  File "/usr/local/lib/python3.8/site-packages/mpld3/_display.py", line 240, in fig_to_html
    Exporter(renderer, close_mpl=False, **kwargs).run(fig)
  File "/usr/local/lib/python3.8/site-packages/mpld3/mplexporter/exporter.py", line 51, in run
    self.crawl_fig(fig)
  File "/usr/local/lib/python3.8/site-packages/mpld3/mplexporter/exporter.py", line 118, in crawl_fig
    self.crawl_ax(ax)
  File "/usr/local/lib/python3.8/site-packages/mpld3/mplexporter/exporter.py", line 123, in crawl_ax
    props=utils.get_axes_properties(ax)):
  File "/usr/local/lib/python3.8/site-packages/mpld3/mplexporter/utils.py", line 268, in get_axes_properties
    'axes': [get_axis_properties(ax.xaxis),
  File "/usr/local/lib/python3.8/site-packages/mpld3/mplexporter/utils.py", line 232, in get_axis_properties
    props['grid'] = get_grid_style(axis)
  File "/usr/local/lib/python3.8/site-packages/mpld3/mplexporter/utils.py", line 242, in get_grid_style
    if axis._gridOnMajor and len(gridlines) > 0:
AttributeError: 'XAxis' object has no attribute '_gridOnMajor'
```

**Comment by vtortola** [comment]
Alright it seems mplexporter did not have this change https://github.com/mpld3/mplexporter/commit/be8e3da62c81fea15a0107f3ae96ba16fc2cc9f7#diff-adfcd5c36ec14ab31873ff8c6a9cc8223587bbefb2e686b74c3f95ad88521021R263 which fixes the issue 🤷
